apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-app
  labels:
    app: healthcare-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcare-app
  template:
    metadata:
      labels:
        app: healthcare-app
    spec:
      containers:
        - name: healthcare-container
          image: healthcare-devsecops:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 5000